export const colors = {
  'normal': 'whitesmoke',
  'fire': 'red',
  'water': 'blue',
  'grass': 'green',
  'electric': 'yellow',
  'ice': 'lightskyblue',
  'fighting': 'firebrick',
  'poison': 'purple',
  'ground': 'saddlebrown',
  'flying': 'royalblue',
  'psychic': 'mediumvioletred',
  'bug': 'lawngreen',
  'rock': 'tan',
  'ghost': 'darkslateblue',
  'dragon': 'navy',
  'dark': 'black',
  'steel': 'slategray',
  'fairy': 'hotpink' 
}